[package]
name = "huione-stake-program"
description = "HUIONE Stake program"
documentation = "https://docs.rs/huione-stake-program"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
bincode = { workspace = true }
log = { workspace = true }
huione-config-program = { workspace = true }
huione-program-runtime = { workspace = true }
huione-sdk = { workspace = true }
huione-vote-program = { workspace = true }
ethnum = { workspace = true }


[dev-dependencies]
assert_matches = { workspace = true }
proptest = { workspace = true }
huione-logger = { workspace = true }
test-case = { workspace = true }

[build-dependencies]
rustc_version = { workspace = true }

[lib]
crate-type = ["lib"]
name = "huione_stake_program"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
