[package]
name = "huione-sbf-rust-many-args-dep"
documentation = "https://docs.rs/huione-sbf-rust-many-args-dep"
version = { workspace = true }
description = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
huione-program = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
