[package]
name = "huione-rpc"
description = "HUIONE RPC"
documentation = "https://docs.rs/huione-rpc"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
base64 = { workspace = true }
bincode = { workspace = true }
bs58 = { workspace = true }
crossbeam-channel = { workspace = true }
dashmap = { workspace = true }
itertools = { workspace = true }
jsonrpc-core =  { workspace = true, features = ["arbitrary_precision"] }
jsonrpc-core-client = { workspace = true, features = ["arbitrary_precision"]  }
jsonrpc-derive = { workspace = true }
jsonrpc-http-server = { workspace = true }
jsonrpc-pubsub = { workspace = true }
libc = { workspace = true }
log = { workspace = true }
rayon = { workspace = true }
regex = { workspace = true }
serde = { workspace = true }
serde_derive = { workspace = true }
serde_json = { workspace = true, features = ["arbitrary_precision"] }
soketto = { workspace = true }
huione-account-decoder = { workspace = true }
huione-client = { workspace = true }
huione-entry = { workspace = true }
huione-faucet = { workspace = true }
huione-gossip = { workspace = true }
huione-ledger = { workspace = true }
huione-measure = { workspace = true }
huione-metrics = { workspace = true }
huione-perf = { workspace = true }
huione-poh = { workspace = true }
huione-rayon-threadlimit = { workspace = true }
huione-rpc-client-api = { workspace = true }
huione-runtime = { workspace = true }
huione-sdk = { workspace = true }
huione-send-transaction-service = { workspace = true }
huione-stake-program = { workspace = true }
huione-storage-bigtable = { workspace = true }
huione-storage-hbase = { workspace = true }
huione-streamer = { workspace = true }
huione-tpu-client = { workspace = true }
huione-transaction-status = { workspace = true }
huione-version = { workspace = true }
huione-vote-program = { workspace = true }
hpl-token = { workspace = true, features = ["no-entrypoint"] }
hpl-name = { workspace = true, features = ["no-entrypoint"] }
stream-cancel = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tokio-util = { workspace = true, features = ["codec", "compat"] }

[dev-dependencies]
serial_test = { workspace = true }
huione-address-lookup-table-program = { workspace = true }
huione-net-utils = { workspace = true }
huione-stake-program = { workspace = true }
symlink = { workspace = true }

[lib]
crate-type = ["lib"]
name = "huione_rpc"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
