[package]
name = "huione-transaction-dos"
publish = false
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
bincode = { workspace = true }
clap = { workspace = true }
log = { workspace = true }
rand = { workspace = true }
rayon = { workspace = true }
huione-clap-utils = { workspace = true }
huione-cli = { workspace = true }
huione-client = { workspace = true }
huione-core = { workspace = true }
huione-faucet = { workspace = true }
huione-gossip = { workspace = true }
huione-logger = { workspace = true }
huione-measure = { workspace = true }
huione-net-utils = { workspace = true }
huione-rpc-client = { workspace = true }
huione-runtime = { workspace = true }
huione-sdk = { workspace = true }
huione-streamer = { workspace = true }
huione-transaction-status = { workspace = true }
huione-version = { workspace = true }

[dev-dependencies]
huione-local-cluster = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
