[package]
name = "huione-thin-client"
description = "Huione Thin Client"
documentation = "https://docs.rs/huione-thin-client"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
bincode = { workspace = true }
log = { workspace = true }
rayon = { workspace = true }
huione-connection-cache = { workspace = true }
huione-rpc-client = { workspace = true }
huione-rpc-client-api = { workspace = true }
huione-sdk = { workspace = true }

[dev-dependencies]
huione-logger = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
