[package]
name = "huione-runtime"
description = "HUIONE runtime"
documentation = "https://docs.rs/huione-runtime"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
arrayref = { workspace = true }
bincode = { workspace = true }
blake3 = { workspace = true }
bv = { workspace = true, features = ["serde"] }
bytemuck = { workspace = true }
byteorder = { workspace = true }
bzip2 = { workspace = true }
crossbeam-channel = { workspace = true }
dashmap = { workspace = true, features = ["rayon", "raw-api"] }
dir-diff = { workspace = true }
flate2 = { workspace = true }
fnv = { workspace = true }
im = { workspace = true, features = ["rayon", "serde"] }
index_list = { workspace = true }
itertools = { workspace = true }
lazy_static = { workspace = true }
log = { workspace = true }
lru = { workspace = true }
lz4 = { workspace = true }
memmap2 = { workspace = true }
modular-bitfield = { workspace = true }
num-derive = { workspace = true }
num-traits = { workspace = true }
num_cpus = { workspace = true }
num_enum = { workspace = true }
once_cell = { workspace = true }
ouroboros = { workspace = true }
percentage = { workspace = true }
rand = { workspace = true }
rayon = { workspace = true }
regex = { workspace = true }
serde = { workspace = true, features = ["rc"] }
serde_derive = { workspace = true }
huione-address-lookup-table-program = { workspace = true }
huione-bpf-loader-program = { workspace = true }
huione-bucket-map = { workspace = true }
huione-compute-budget-program = { workspace = true }
huione-config-program = { workspace = true }
huione-frozen-abi = { workspace = true }
huione-frozen-abi-macro = { workspace = true }
huione-loader-v4-program = { workspace = true }
huione-measure = { workspace = true }
huione-metrics = { workspace = true }
huione-perf = { workspace = true }
huione-program-runtime = { workspace = true }
huione-rayon-threadlimit = { workspace = true }
huione-sdk = { workspace = true }
huione-stake-program = { workspace = true }
huione-system-program = { workspace = true }
huione-vote-program = { workspace = true }
huione-zk-token-proof-program = { workspace = true }
huione-zk-token-sdk = { workspace = true }
static_assertions = { workspace = true }
strum = { workspace = true, features = ["derive"] }
strum_macros = { workspace = true }
symlink = { workspace = true }
tar = { workspace = true }
tempfile = { workspace = true }
thiserror = { workspace = true }
zstd = { workspace = true }
portable-atomic = { workspace = true }
ethnum = { workspace = true }
[lib]
crate-type = ["lib"]
name = "huione_runtime"

[dev-dependencies]
assert_matches = { workspace = true }
ed25519-dalek = { workspace = true }
libsecp256k1 = { workspace = true }
memoffset = { workspace = true }
rand_chacha = { workspace = true }
huione-logger = { workspace = true }
static_assertions = { workspace = true }
test-case = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[build-dependencies]
rustc_version = { workspace = true }

[[bench]]
name = "prioritization_fee_cache"
