[package]
name = "huione-transaction-status"
description = "huione transaction status types"
documentation = "https://docs.rs/huione-transaction-status"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
Inflector = { workspace = true }
base64 = { workspace = true }
bincode = { workspace = true }
borsh = { workspace = true }
bs58 = { workspace = true }
lazy_static = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
serde_derive = { workspace = true }
serde_json = { workspace = true, features = ["arbitrary_precision"] }
thiserror = { workspace = true }
huione-account-decoder = { workspace = true }
huione-address-lookup-table-program = { workspace = true }
huione-sdk = { workspace = true }
huione-measure = { workspace = true }
huione-metrics = { workspace = true }
huione-runtime = { workspace = true }
huione-vote-program = { workspace = true }
hpl-associated-token-account = { workspace = true }
hpl-memo = { workspace = true }
hpl-token = { workspace = true }
hpl-nft = { workspace = true }
hpl-name = { workspace = true }


[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
