[package]
name = "huione-loader-v4-program"
description = "Huione Loader v4"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
log = { workspace = true }
rand = { workspace = true }
huione-measure = { workspace = true }
huione-program-runtime = { workspace = true }
huione-sdk = { workspace = true }
huione_rbpf = { workspace = true }

[dev-dependencies]
bincode = { workspace = true }

[lib]
crate-type = ["lib"]
name = "huione_loader_v4_program"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
