[package]
name = "huione-stake-accounts"
description = "Blockchain, Rebuilt for Scale"
documentation = "https://docs.rs/huione-stake-accounts"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
clap = { workspace = true }
huione-clap-utils = { workspace = true }
huione-cli-config = { workspace = true }
huione-remote-wallet = { workspace = true, features = ["default"] }
huione-rpc-client = { workspace = true, features = ["default"] }
huione-rpc-client-api = { workspace = true }
huione-sdk = { workspace = true }
huione-stake-program = { workspace = true }
huione-version = { workspace = true }

[dev-dependencies]
huione-runtime = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
