[package]
name = "huione-zk-token-proof-program"
description = "HUIONE Zk Token Proof Program"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
bytemuck = { workspace = true, features = ["derive"] }
getrandom = { workspace = true, features = ["dummy"] }
num-derive = { workspace = true }
num-traits = { workspace = true }
huione-program-runtime = { workspace = true }
huione-sdk = { workspace = true }
huione-zk-token-sdk = { workspace = true }
