[package]
name = "huione-rpc-client-nonce-utils"
description = "Huione RPC Client Nonce Utilities"
documentation = "https://docs.rs/huione-nonce-client"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
clap = "2.33.0"
huione-clap-utils = { workspace = true }
huione-rpc-client = { workspace = true }
huione-sdk = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
futures = { workspace = true }
serde_json = { workspace = true, features = ["arbitrary_precision"] }
huione-account-decoder = { workspace = true }
huione-rpc-client-api = { workspace = true }
tokio = { workspace = true, features = ["full"] }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
