[package]
name = "huione-send-transaction-service"
description = "HUIONE send transaction service"
documentation = "https://docs.rs/huione-send-transaction-service"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
crossbeam-channel = { workspace = true }
log = { workspace = true }
huione-client = { workspace = true }
huione-measure = { workspace = true }
huione-metrics = { workspace = true }
huione-runtime = { workspace = true }
huione-sdk = { workspace = true }
huione-tpu-client = { workspace = true }

[dev-dependencies]
huione-logger = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
